language: python
python:
    - 2.7

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y
        libvorbis-dev
        libsdl1.2-dev
        libsdl-mixer1.2-dev
        libsdl-image1.2-dev
        libsdl-ttf2.0-dev
        libportmidi-dev
        libsoundtouch-dev
        libportaudio2

install:
    - pip install pytest
    - pip install cython
    - pip install -r requirements.txt
    - python setup.py build_ext --inplace --force

script:
    - pytest
