language: python

matrix:
    include:
        - name: Git lint
          env:
              - GIT_COMMIT=1
          before_install: pass
          install:
              - pip install gitlint
          script:
              - gitlint --commits origin..HEAD

        - env: GIT_COMMIT=0
          python: 2.7
        - env: GIT_COMMIT=0
          python: 3.4
        - env: GIT_COMMIT=0
          python: 3.5
        - env: GIT_COMMIT=0
          python: 3.6
        - env: GIT_COMMIT=0
          python: 3.7

    allow_failures:
        - env: GIT_COMMIT=0
          python: 3.4
        - env: GIT_COMMIT=0
          python: 3.5
        - env: GIT_COMMIT=0
          python: 3.6
        - env: GIT_COMMIT=0
          python: 3.7

before_install:
    - LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH
    - sudo apt-get -qq update
    - sudo apt-get install -y
        libogg-dev
        libportmidi-dev
        libsdl-image1.2-dev
        libsdl-mixer1.2-dev
        libsdl-ttf2.0-dev
        libsdl1.2-dev
        libsoundtouch-dev
        libswscale-dev
        libtheora-dev
        libvorbis-dev
        mesa-utils
        portaudio19-dev
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH
    - sudo apt-get -q update
    - sudo apt-get install -y gcc-4.9 g++-4.9

install:
    - pip install pytest
    - pip install cython
    - pip install -r requirements.txt
    # build ext
    - python setup.py build_ext --inplace --force

before_script:
    # hack: GUI tests
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3   # give xvfb some time to start
    - export SDL_AUDIODRIVER=disk

script:
    - pytest fofix

notifiations:
    email: false
