language: python
python:
    - 2.7

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y
        freeglut3-dev
        libgl1-mesa-dev
        libgl1-mesa-glx
        libglib2.0-dev
        libglu1-mesa-dev
        libogg-dev
        libportmidi-dev
        libsdl-image1.2-dev
        libsdl-mixer1.2-dev
        libsdl-ttf2.0-dev
        libsdl1.2-dev
        libsoundtouch-dev
        libswscale-dev
        libtheora-dev
        libvorbis-dev
        portaudio19-dev
        mesa-utils
        xpra
        xvfb

install:
    - pip install pytest
    - pip install cython
    - pip install -r requirements.txt
    - export PY_PACKAGES=`pip --version | cut -d' ' -f4`
    - wget https://bitbucket.org/jibalamy/cerealizer/raw/ffbb9283c507c2bb7191bb413722a316e9c0718b/__init__.py2 -O $PY_PACKAGES/cerealizer/__init__.py2
    - python setup.py build_ext --inplace --force

before_script:
    - export DISPLAY=:99
    - export LIBGL_ALWAYS_SOFTWARE=1
    - export SDL_VIDEODRIVER=dummy
    - export SDL_AUDIODRIVER=disk
    - xpra --xvfb="Xorg +extension GLX +extension RANDR +extension RENDER -config `pwd`/test/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log"  start :99
    - glxinfo

script:
    - pytest fofix

notifiations:
    email: false
