language: python
python:
    - 2.7
dist: trusty

matrix:
    include:
        - name: Git lint
          env:
              - GIT_COMMIT=1
          before_install: continue
          install:
              - pip install gitlint
          before_script: continue
          script:
              - gitlint --commits origin..HEAD

        - env: GIT_COMMIT=0
          python: 2.7
          os: linux
        - env: GIT_COMMIT=0
          python: 3.6
          os: linux
        #- env: GIT_COMMIT=0
        #  python: pypy
        #  os: linux

        - env:
              - GIT_COMMIT=0
              - PY_VERSION=2.7
          language: generic
          os: osx
        - env:
              - GIT_COMMIT=0
              - PY_VERSION=3.6.2
          language: generic
          os: osx

    allow_failures:
        - os: osx
        - env: GIT_COMMIT=0
          python: 3.6
        #- env: GIT_COMMIT=0
        #  python: pypy

before_install:
    - LD_LIBRARY_PATH=/usr/local/lib64/:$LD_LIBRARY_PATH
    - export LD_LIBRARY_PATH
    - echo $TRAVIS_OS_NAME
    - |
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo apt-get -qq update;
        sudo apt-get install -y \
          libogg-dev \
          libportmidi-dev \
          libsdl-image1.2-dev \
          libsdl-mixer1.2-dev \
          libsdl-ttf2.0-dev \
          libsdl1.2-dev \
          libsoundtouch-dev \
          libswscale-dev \
          libtheora-dev \
          libvorbis-dev \
          mesa-utils \
          portaudio19-dev;
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y;
        sudo apt-get -q update;
        sudo apt-get install -y gcc-4.9 g++-4.9;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        brew update;
        brew install \
          glib \
          libogg \
          theora \
          libvorbis \
          portaudio \
          portmidi \
          ffmpeg \
          sdl --universal \
          sdl_image \
          sdl_mixer \
          sdl_ttf;
        # soundtouch
        wget https://www.surina.net/soundtouch/soundtouch-2.0.0.zip;
        unzip soundtouch-2.0.0.zip;
        cd soundtouch;
        ./bootstrap;
        ./configure;
        make;
        make install;
        cd ..;
        # pyenv
        brew outdated pyenv || brew upgrade pyenv;
        brew install pyenv-virtualenv;
        eval "$(pyenv init -)";
        eval "$(pyenv virtualenv-init -)";
        pyenv install $PY_VERSION;
        pyenv virtualenv $PY_VERSION venv;
        pyenv activate venv;
        pip install --upgrade pip;

        pyenv virtualenvs;
        pyenv version;
        python --version;
      fi

install:
    - pip install flake8
    - pip install pytest
    - pip install cython
    - pip install configparser
    - pip install -r requirements.txt
    # build ext
    - python setup.py build_ext --inplace --force

before_script:
    # hack: GUI tests
    - export DISPLAY=:99
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then (nohup Xvfb :99; echo "xvfb")& fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
    - sleep 3   # give xvfb some time to start
    - export SDL_AUDIODRIVER=disk

script:
    - python setup.py check
    #- pytest fofix
    - coverage run --source='fofix' --omit='fofix/tests/*' setup.py test
    - coverage html
    - flake8 --config=setup.cfg

notifiations:
    email: false
